# Generated by Django 4.2.5 on 2023-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_registrationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('school_name', models.CharField(max_length=50)),
                ('shl_cmplted_year', models.IntegerField()),
                ('shl_percent', models.IntegerField()),
                ('inter_clg_name', models.CharField(max_length=50)),
                ('clg_cmplted_year', models.IntegerField()),
                ('inter_percent', models.IntegerField()),
                ('graduationc_clg_name', models.CharField(max_length=50)),
                ('grdtion_cmplted_year', models.IntegerField()),
                ('grdtion_percent', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
