# Generated by Django 4.2.5 on 2023-10-17 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('loc', models.CharField(max_length=50)),
                ('marks', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('iname', models.CharField(max_length=50)),
                ('fee', models.BigIntegerField()),
                ('students', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.students')),
            ],
        ),
    ]
