# Generated by Django 4.2.5 on 2023-10-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('models', models.CharField(max_length=50)),
            ],
        ),
    ]
