# Generated by Django 4.2.5 on 2023-11-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolist_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.EmailField(max_length=20)),
                ('upass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.EmailField(max_length=20)),
                ('upass', models.CharField(max_length=20)),
                ('ucpass', models.CharField(max_length=20)),
            ],
        ),
    ]
