# Generated by Django 4.2.5 on 2023-10-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('first_name', models.CharField(max_length=50, primary_key=10, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
