# Generated by Django 4.2.5 on 2023-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('course', models.CharField(max_length=50)),
                ('fee', models.IntegerField()),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
