# Generated by Django 4.2.5 on 2023-10-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('timings', models.TimeField()),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_experience', models.CharField(max_length=50)),
                ('trainer_mode', models.CharField(max_length=50)),
            ],
        ),
    ]
